name: Build and Release

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.getversion.outputs.ver }}
      cver: ${{ steps.getversion.outputs.cver }}
    steps:
      -
        name: Get version
        id: getversion
        run: |
          ver=`curl https://api.github.com/repos/cloudflare/cloudflared/releases/latest | jq -r '.tag_name'`
          cver=`curl https://api.github.com/repos/lmq8267/cloudflared/releases/latest | jq -r '.tag_name'`
          echo "ver=${ver}" >> $GITHUB_OUTPUT
          echo "cver=${cver}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.ver != needs.check.outputs.cver }}
    steps:
      - 
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.7
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Build
        run: |
          git clone https://github.com/cloudflare/cloudflared -b ${{ needs.check.outputs.ver }} ../src
          cd ../src
          sudo apt-get remove upx-ucl
          sudo apt-get install upx-ucl=3.95-1
          curl -k -S -o /opt/src/strip --connect-timeout 10 --retry 3 https://cdn.jsdelivr.net/gh/lmq8267/cloudflared/strip
          chmod 777 /opt/src/strip
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat make cloudflared
          upx --lzma --best cloudflared
      - 
        name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          tag_name: ${{ needs.check.outputs.ver }}
          files: |
              ../src/cloudflared
     
