name: 编译mipsel版cloudflared

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: # 允许手动触发
env:
  TZ: Asia/Shanghai

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      tag_exists: ${{ steps.check-tag.outputs.tag_exists }}
    steps:
      - name: Get latest version
        id: get-version
        run: |
          # 获取cloudflare/cloudflared的最新版本，并设置为"version"输出
          echo "::set-output name=version::$(curl -s https://api.github.com/repos/cloudflare/cloudflared/releases/latest | jq -r '.tag_name')"
        shell: bash

      - name: Check if tag exists
        id: check-tag
        run: |
          # 检查我们的仓库中是否存在与cloudflare/cloudflared的最新版本相对应的标签，并将结果设置为"tag_exists"输出
          TAG_EXISTS=$(curl --silent --head --fail https://github.com/${{ github.repository }}/releases/tag/${{ steps.get-version.outputs.version }} > /dev/null; echo $?)
          echo "::set-output name=tag_exists::$TAG_EXISTS"
        shell: bash

  build:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.tag_exists == '1'
    steps:
      - 
        name: 安装go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5
      -
        name: 检查代码仓库
        uses: actions/checkout@v3
      - 
        name: 编译
        run: |
          git clone https://github.com/cloudflare/cloudflared -b ${{ needs.check.outputs.ver }} ../src
          git clone https://github.com/${{ github.repository }}.git /opt/st
          cd ../src
          sudo timedatectl set-timezone "Asia/Shanghai"
          tar -xvf /opt/st/upx-3.95-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/upx-3.95-amd64_linux/upx
          chmod 777 /opt/st/strip
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat make cloudflared
          /opt/st/strip cloudflared
          /opt/upx-3.95-amd64_linux/upx --lzma --best cloudflared
          echo $(md5sum cloudflared | awk '{print $1;}') >MD5.txt
          echo "build_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - 
        name: 发布Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          tag_name: ${{ needs.check.outputs.ver }}
          body: |
           > ### 编译时间 ：${{ env.build_time }}

           **[官方更新说明](https://github.com/cloudflare/cloudflared/releases)**
          files: |
              ../src/cloudflared
              ../src/MD5.txt
      - 
       name: 删除工作流
       uses: GitRML/delete-workflow-runs@main
       with:
        token: ${{ secrets.c8 }}
        retain_days: 2
        keep_minimum_runs: 0

  release:
    needs: build
    runs-on: ubuntu-latest
      
    steps:
      - name: 创建新的 release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.check.outputs.ver }}
          release_name: Release ${{ needs.check.outputs.ver }}
          draft: false
          prerelease: false